
# This file is automatically generated, you probably don't want to edit this

asvdOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "asvdOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            indeps = NULL,
            step = "screen",
            alpha = 0.5,
            autoAlpha = TRUE,
            lambdaSel = "min",
            polyOrder = 2,
            nboot = 100,
            showBeta = TRUE,
            formulaText = "",
            interIndex = 1,
            nfolds = 5,
            showPlot = TRUE, ...) {

            super$initialize(
                package="ASVD",
                name="asvd",
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep)
            private$..indeps <- jmvcore::OptionVariables$new(
                "indeps",
                indeps)
            private$..step <- jmvcore::OptionList$new(
                "step",
                step,
                options=list(
                    "screen",
                    "final"),
                default="screen")
            private$..alpha <- jmvcore::OptionNumber$new(
                "alpha",
                alpha,
                default=0.5,
                min=0,
                max=1)
            private$..autoAlpha <- jmvcore::OptionBool$new(
                "autoAlpha",
                autoAlpha,
                default=TRUE)
            private$..lambdaSel <- jmvcore::OptionList$new(
                "lambdaSel",
                lambdaSel,
                options=list(
                    "min",
                    "1se"),
                default="min")
            private$..polyOrder <- jmvcore::OptionNumber$new(
                "polyOrder",
                polyOrder,
                default=2,
                min=1)
            private$..nboot <- jmvcore::OptionNumber$new(
                "nboot",
                nboot,
                default=100)
            private$..showBeta <- jmvcore::OptionBool$new(
                "showBeta",
                showBeta,
                default=TRUE)
            private$..formulaText <- jmvcore::OptionString$new(
                "formulaText",
                formulaText,
                default="")
            private$..interIndex <- jmvcore::OptionNumber$new(
                "interIndex",
                interIndex,
                default=1)
            private$..nfolds <- jmvcore::OptionNumber$new(
                "nfolds",
                nfolds,
                default=5,
                min=3,
                max=20)
            private$..showPlot <- jmvcore::OptionBool$new(
                "showPlot",
                showPlot,
                default=TRUE)

            self$.addOption(private$..dep)
            self$.addOption(private$..indeps)
            self$.addOption(private$..step)
            self$.addOption(private$..alpha)
            self$.addOption(private$..autoAlpha)
            self$.addOption(private$..lambdaSel)
            self$.addOption(private$..polyOrder)
            self$.addOption(private$..nboot)
            self$.addOption(private$..showBeta)
            self$.addOption(private$..formulaText)
            self$.addOption(private$..interIndex)
            self$.addOption(private$..nfolds)
            self$.addOption(private$..showPlot)
        }),
    active = list(
        dep = function() private$..dep$value,
        indeps = function() private$..indeps$value,
        step = function() private$..step$value,
        alpha = function() private$..alpha$value,
        autoAlpha = function() private$..autoAlpha$value,
        lambdaSel = function() private$..lambdaSel$value,
        polyOrder = function() private$..polyOrder$value,
        nboot = function() private$..nboot$value,
        showBeta = function() private$..showBeta$value,
        formulaText = function() private$..formulaText$value,
        interIndex = function() private$..interIndex$value,
        nfolds = function() private$..nfolds$value,
        showPlot = function() private$..showPlot$value),
    private = list(
        ..dep = NA,
        ..indeps = NA,
        ..step = NA,
        ..alpha = NA,
        ..autoAlpha = NA,
        ..lambdaSel = NA,
        ..polyOrder = NA,
        ..nboot = NA,
        ..showBeta = NA,
        ..formulaText = NA,
        ..interIndex = NA,
        ..nfolds = NA,
        ..showPlot = NA)
)

asvdResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "asvdResults",
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        metricsTable = function() private$.items[["metricsTable"]],
        asvdTable = function() private$.items[["asvdTable"]],
        asvdVisual = function() private$.items[["asvdVisual"]],
        elnetPlot = function() private$.items[["elnetPlot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="ASVD Protocol")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="ASVD Log"))
            self$add(jmvcore::Table$new(
                options=options,
                name="metricsTable",
                title="Model Performance (Bootstrap)",
                rows=1,
                columns=list(
                    list(
                        `name`="metric", 
                        `title`="Metric", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Original", 
                        `type`="number"),
                    list(
                        `name`="lower", 
                        `title`="Lower CI", 
                        `type`="number"),
                    list(
                        `name`="upper", 
                        `title`="Upper CI", 
                        `type`="number"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="asvdTable",
                title="ASVD Variable Importance (Anova SS)",
                columns=list(
                    list(
                        `name`="var", 
                        `title`="Predictor", 
                        `type`="text"),
                    list(
                        `name`="beta", 
                        `title`="Beta (Std)", 
                        `type`="number"),
                    list(
                        `name`="lmg", 
                        `title`="SS Share (Raw)", 
                        `type`="number"),
                    list(
                        `name`="lmg_p", 
                        `title`="Contribution %", 
                        `type`="number"),
                    list(
                        `name`="lower", 
                        `title`="Lower CI", 
                        `type`="number"),
                    list(
                        `name`="upper", 
                        `title`="Upper CI", 
                        `type`="number"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="asvdVisual",
                title="ASVD Interaction Analysis",
                width=600,
                height=450,
                renderFun=".renderAsvd"))
            self$add(jmvcore::Image$new(
                options=options,
                name="elnetPlot",
                title="Elastic Net MSE & Trace",
                width=600,
                height=400,
                renderFun=".plotElnet"))}))

asvdBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "asvdBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "ASVD",
                name = "asvd",
                version = c(1,5,0),
                options = options,
                results = asvdResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' ASVD Protocol
#'
#' 
#' @param data .
#' @param dep .
#' @param indeps .
#' @param step .
#' @param alpha .
#' @param autoAlpha .
#' @param lambdaSel .
#' @param polyOrder .
#' @param nboot .
#' @param showBeta .
#' @param formulaText .
#' @param interIndex .
#' @param nfolds .
#' @param showPlot .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$metricsTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$asvdTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$asvdVisual} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$elnetPlot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$metricsTable$asDF}
#'
#' \code{as.data.frame(results$metricsTable)}
#'
#' @export
asvd <- function(
    data,
    dep,
    indeps,
    step = "screen",
    alpha = 0.5,
    autoAlpha = TRUE,
    lambdaSel = "min",
    polyOrder = 2,
    nboot = 100,
    showBeta = TRUE,
    formulaText = "",
    interIndex = 1,
    nfolds = 5,
    showPlot = TRUE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("asvd requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if ( ! missing(indeps)) indeps <- jmvcore::resolveQuo(jmvcore::enquo(indeps))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL),
            `if`( ! missing(indeps), indeps, NULL))


    options <- asvdOptions$new(
        dep = dep,
        indeps = indeps,
        step = step,
        alpha = alpha,
        autoAlpha = autoAlpha,
        lambdaSel = lambdaSel,
        polyOrder = polyOrder,
        nboot = nboot,
        showBeta = showBeta,
        formulaText = formulaText,
        interIndex = interIndex,
        nfolds = nfolds,
        showPlot = showPlot)

    analysis <- asvdClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

